carpark/urls.py
from carpark import views
from taxi.decorators import group_required


from django.conf.urls import url

urlpatterns = [
    url("^create", group_required('Manager')(views.CarFormView.as_view()), name="create_car"),
    url("^add-driver", group_required('Manager')(views.AddDriverFormView.as_view()), name="add_driver"),
    url("^add-trip", group_required('Client')(views.AddTripFormView.as_view()), name="add_trip"),
    url("^non-accepted-trips", group_required('Driver')(views.NonAcceptedTripsView.as_view()), name="non_trip"),
    url("^accept-trip/(?P<trip_id>\d+)", group_required('Driver')(views.AcceptTripView.as_view()), name="accept"),
    url("^close-trip/(?P<trip_id>\d+)", group_required('Driver')(views.CloseTripView.as_view()), name="close"),
     url("^non-closed-trips", group_required('Driver')(views.NonClosedTripsView.as_view()), name="nonclosed_trips")
]

taxi/urls.py
from django.contrib import admin
from django.urls import path, reverse
from django.conf.urls import include, url
from django.http import HttpResponseRedirect

urlpatterns = [
    path('admin/', admin.site.urls),
    url('user/', include(('authorization.urls', 'auth'), namespace='auth')),
    url('cars/', include(('carpark.urls', 'carpark'), namespace='carpark')),
    url('^$', lambda x: HttpResponseRedirect(reverse('auth:base'))),
]

carpark/models.py
import datetime


from django.core.validators import RegexValidator
from django.contrib.auth.models import User, Group
from django.db import models
from django.core.exceptions import ValidationError


def is_driver_validator(user):
    user = User.objects.get(id=user)
    g = Group.objects.get(name="Driver")
    if g not in user.groups.all():
        raise ValidationError("user is not a driver")

# Create your models here.
class Car(models.Model):
    number = models.CharField(max_length=9, 
                              validators=[RegexValidator(regex=r"^[АВЕКМНОРСТУХ][0-9]{3}[АВЕКМНОРСТУХ]{2}[0-9]{0,3}")])
    driver = models.OneToOneField(User, on_delete=models.CASCADE, validators=[is_driver_validator])
    brand = models.CharField(max_length=20)
    model = models.CharField(max_length=30)
    color = models.CharField(max_length=20)

    def __str__(self):
        return "%s %s - %s" % (self.brand, self.model, self.number)


class Point(models.Model):
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    lng = models.DecimalField(max_digits=9, decimal_places=6)


class Trip(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, null=True, blank=True)
    startpoint = models.TextField()
    startpoint_coordinate = models.ForeignKey(Point, on_delete=models.CASCADE, related_name="strt_crd")
    endpoint = models.TextField()
    endpoint_coordinate = models.ForeignKey(Point, on_delete=models.CASCADE, related_name="end_crd")
    create_time = models.DateTimeField(default=datetime.datetime.now)
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)

    def is_done(self):
        return True if self.end_time else False

    def __str__(self):
        return "%s - %s - %s" % (self.startpoint, self.endpoint, "Done" if self.is_done() else "In process")

carpark/forms.py
import asyncio
import aiohttp
import re
import requests



from django.forms import ModelForm, Form, ModelChoiceField, ChoiceField, CharField, HiddenInput
from carpark.models import Car, Trip, Point
from django.contrib.auth.models import User, Group
from authorization.models import Grade
from manager.price_counter import PriceCounter
from taxi.settings import GOOGLE_API_KEY




async def count_price(obj):
    print("counting started")
    async with aiohttp.ClientSession() as session:
        async with session.get("https://maps.googleapis.com/maps/api/directions/json?origin=%s,%s&destination=%s,%s&mode=driving&key=%s" 
                % (obj.startpoint_coordinate.lat,
                   obj.startpoint_coordinate.lng,
                   obj.endpoint_coordinate.lat,
                   obj.endpoint_coordinate.lng,
                      GOOGLE_API_KEY)) as resp:
            print("https://maps.googleapis.com/maps/api/directions/json?origin=%s,%s&destination=%s,%s&mode=driving&key=%s" 
                % (obj.startpoint_coordinate.lat,
                   obj.startpoint_coordinate.lng,
                   obj.endpoint_coordinate.lat,
                   obj.endpoint_coordinate.lng,
                      GOOGLE_API_KEY))
            
            # 
            j = await resp.json()
            p1 = j["routes"][0]["legs"][0]["distance"]["value"]
            print(p1)
            
            counter = PriceCounter()
            obj.price = counter.count_price(p1/1000)
            obj.save()

    
    print("DOne!")


async def save_all_trip(obj, client):
    obj.client = client
    obj.save()


class CarForm(ModelForm):
    class Meta:
        model = Car
        exclude = []

    def __init__(self, *args, **kwargs):
        super(CarForm, self).__init__(*args, **kwargs)
        self.fields['driver'].queryset = User.objects.filter(groups__name="Driver")


class AddDriverForm(Form):
    user = ModelChoiceField(queryset=User.objects.filter(groups__name="Client"))

    def save(self):
        u = self.cleaned_data['user']
        Group.objects.get(name="Client").user_set.remove(u)
        Group.objects.get(name="Driver").user_set.add(u)


class AddTripForm(Form):

    # class Meta:
    #     model = Trip
    #     fields = ['startpoint', 'startpoint_coordinate', 'endpoint', 'endpoint_coordinate']
    startpoint = CharField(widget=HiddenInput())
    endpoint = CharField(widget=HiddenInput())
    start_lat = CharField(widget=HiddenInput())
    start_lng = CharField(widget=HiddenInput())
    end_lat = CharField(widget=HiddenInput())
    end_lng = CharField(widget=HiddenInput())

    def save(self, client, *args, **kwargs):
        # obj = super(AddTripForm, self).save(commit=False, *args, **kwargs)
        print("ok")
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

        print("?")
        obj = Trip(startpoint=self.cleaned_data['startpoint'], endpoint=self.cleaned_data['endpoint'])
        
        print("exe")

        obj.startpoint_coordinate =  Point.objects.create(lat=self.cleaned_data['start_lat'], 
                                                          lng=self.cleaned_data['start_lng'])
        obj.endpoint_coordinate =  Point.objects.create(lat=self.cleaned_data['end_lat'], 
                                                          lng=self.cleaned_data['end_lng'])
        loop.run_until_complete(asyncio.wait([count_price(obj), save_all_trip(obj, client)]))
        loop.close()
        
        print("to user")


        
        


        



class RateDriver(Form):

    driver = HiddenInput()
    value = ChoiceField(choices=[(x, x) for x in range(6)])

    def save(self, client, *args, **kwargs):
        try:
            driver = User.objects.get(self.cleaned_data['driver'])
            grade = Grade.objects.filter(driver=driver, client=client)
            if grade:
                grade.value = value
                grade.save()
            elif driver.groups.filter(name="Driver").exists():
                g = Grade.objects.create(driver=driver, client=client, value=value)
        except:
            pass    

carpark/views.py
from datetime import datetime


from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from carpark.forms import CarForm, AddDriverForm, AddTripForm
from django.http import HttpResponse
from django.views.generic import ListView, View
from django.views.generic.edit import FormView
from .models import Car, Trip

# Create your views here.

class CarFormView(LoginRequiredMixin, FormView):
    form_class = CarForm
    template_name = "carpark/car.html"
    success_url = "/"

    def form_valid(self, form):
        form.save()
        return super(CarFormView, self).form_valid(form)


class AddDriverFormView(LoginRequiredMixin, FormView):
    form_class = AddDriverForm
    template_name = "carpark/driver.html"
    success_url = "/"

    def form_valid(self, form):
        form.save()
        return super(AddDriverFormView, self).form_valid(form)


class AddTripFormView(LoginRequiredMixin, FormView):
    form_class = AddTripForm
    template_name = "carpark/trip.html"
    success_url = "/"

    def form_valid(self, form):
        form.save(client=self.request.user)
        return super(AddTripFormView, self).form_valid(form)


class NonAcceptedTripsView(LoginRequiredMixin, ListView):
    model = Trip
    template_name = "carpark/trips.html"

    def dispatch(self, request):
        car = Car.objects.get(driver=request.user)
        if Trip.objects.filter(car=car, end_time=None).exists():
            return HttpResponse("You have a trip!")
        return super(NonAcceptedTripsView, self).dispatch(request)


    def get_queryset(self):
        return Trip.objects.filter(car=None)


class AcceptTripView(LoginRequiredMixin, View):

    def get(self, request, trip_id):
        try:
            car = Car.objects.get(driver=request.user)
            if Trip.objects.filter(car=car, end_time=None).exists():
                return HttpResponse("Trip is already exists")
            t = Trip.objects.get(id=trip_id)
            if t.car:
                return HttpResponse("sorry")
            else:
                t.car = Car.objects.get(driver=request.user)
                t.save()
                return HttpResponse("OK")
        except:
            return HttpResponse("Doesn't exist")


class NonClosedTripsView(LoginRequiredMixin, ListView):
    model = Trip
    template_name = "carpark/trips_opened.html"

    def dispatch(self, request):
        car = Car.objects.get(driver=request.user)
        self.queryset = Trip.objects.filter(car=car, end_time=None)
        return super(NonClosedTripsView, self).dispatch(request)




class CloseTripView(LoginRequiredMixin, View):

    def get(self, request, trip_id):
        try:
            t = Trip.objects.get(id=trip_id)
            car = Car.objects.get(driver=request.user)
            if t.car and t.car == car:
                t.end_time = datetime.now()
                t.save()
                return HttpResponse("OK")
            else:
                return HttpResponse("sorry")
        except:
            return HttpResponse("Doesn't exist")

carpark/templates/carpark/car.html
{% extends 'base.html' %}
    {% block title %}Создать авто{% endblock %}
  {% block content %}
  <div class="container">
    <div class="jumbotron">
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Добавить</button>
    </form>
    </div>
    </div>
    {% endblock %}

carpark/templates/carpark/driver.html
{% extends 'base.html' %}
    {% block title %} Создать авто {% endblock %}
  {% block content %}
  <div class="container">
    <div class="jumbotron">
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Добавить</button>
    </form>
  </div>
  </div>
  {% endblock %}

carpark/templates/carpark/trip.html
{% extends 'base.html'%}
    {% block title %}Создать путь{% endblock %}
    
  {% block content %}
  <style type="text/css">
      #map {
        height: 400px;
        width: 100%;
      }
    </style>
    
    <div class="container">
    <div class="jumbotron">
    <div id="map"></div>
    <form action="" id="frm" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button id="sbm" class="btn" type="button">Добавить</button>
    </form>
    </div>
    </div>
    <script>
      var map;
      var markersCount = 0;
      var markerStart;
      var markerEnd;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 55.797257, lng: 49.189824},
          zoom: 10,
          streetViewControl: false,
          mapTypeId: google.maps.MapTypeId.ROADMAP,
          disableDefaultUI: true,
          enableMarkers: true
        });

        

        var placeMarker = function(latLng, mark){
            var marker = new google.maps.Marker({
              position: new google.maps.LatLng(latLng.lat(), latLng.lng()),
              map: map,
              draggable:true,
              title: mark
            });
            
            return marker;
        };

        map.addListener('click', function(e){
          switch(markersCount){
            case 0:
              markerStart = placeMarker(e.latLng, "Отправление");
              markersCount++;
              break;
            case 1:
              markerEnd = placeMarker(e.latLng, "Прибытие");
              markersCount++;
              break;
          } 
          
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key={{ google_key }}&callback=initMap&libraries=places&language=ru"
    async defer></script>
    <script type="text/javascript">
      var check = 0;
      function setMarkersAddress(marker, field, field_lat, field_lng){
        var g = new google.maps.Geocoder();
        g.geocode({ location:  marker.getPosition()}, function(results, status){
          if(status == "OK"){
            var res = results[0].address_components
            var s = "";
            for(i=res.length-1; i>=0; i--){
              s += res[i].long_name + " "
            }
            field.value = s;
            field_lat.value = marker.getPosition().lat();
            field_lng.value = marker.getPosition().lng();
          }
          if(check == 1){
            form = document.getElementById('frm');
            form.submit();
          }else{
            check++;
          }
        });
      };
      document.getElementById("sbm").onclick = function(){
        
        setMarkersAddress(markerStart, document.getElementById('id_startpoint'), document.getElementById('id_start_lat'), document.getElementById('id_start_lng'));
        setMarkersAddress(markerEnd, document.getElementById('id_endpoint'), document.getElementById('id_end_lat'), document.getElementById('id_end_lng'));
        
      };
      </script>
    {% endblock %}

carpark/templates/carpark/trips.html
{% extends 'base.html' %}
    {% block title %}Создать авто{% endblock %}
  {% block content %}
  <div class="container">
    <div class="jumbotron">
    {% for trip in object_list %}
      <div class="row"><a href="{% url 'carpark:accept' trip_id=trip.id %}">{{ trip.client }} - {{ trip.startpoint }} - {{ trip.endpoint }} </a>  </div>
    {% endfor %}
  </div>
  </div>
  {% endblock %}

carpark/templates/carpark/trips_opened.html
{% extends 'base.html' %}
    {% block title %}Создать авто{% endblock %}
    {% block content %}
  <div class="container">
    <div class="jumbotron">
  <ul>
    {% for trip in object_list %}
      <li> <a href="{% url 'carpark:close' trip_id=trip.id %}">{{ trip.client }} - {{ trip.startpoint }} - {{ trip.endpoint }} </a>  </li>
    {% endfor %}
  </ul>
  </div>
  </div>
  {% endblock %}