carpark/urls.py
from carpark import views
from taxi.decorators import group_required


from django.conf.urls import url

urlpatterns = [
    url("^create", group_required('Manager')(views.CarFormView.as_view()), name="create_car"),
    url("^add-driver", group_required('Manager')(views.AddDriverFormView.as_view()), name="add_driver"),
    url("^add-trip", group_required('Client')(views.AddTripFormView.as_view()), name="add_trip"),
    url("^non-accepted-trips", group_required('Driver')(views.NonAcceptedTripsView.as_view()), name="non_trip"),
    url("^accept-trip/(?P<trip_id>\d+)", group_required('Driver')(views.AcceptTripView.as_view()), name="accept"),
    url("^close-trip/(?P<trip_id>\d+)", group_required('Driver')(views.CloseTripView.as_view()), name="close"),
     url("^non-closed-trips", group_required('Driver')(views.NonClosedTripsView.as_view()), name="nonclosed_trips")
]

taxi/urls.py
from django.contrib import admin
from django.urls import path, reverse
from django.conf.urls import include, url
from django.http import HttpResponseRedirect

urlpatterns = [
    path('admin/', admin.site.urls),
    url('user/', include(('authorization.urls', 'auth'), namespace='auth')),
    url('cars/', include(('carpark.urls', 'carpark'), namespace='carpark')),
    url('^$', lambda x: HttpResponseRedirect(reverse('auth:base'))),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}">
  </head>
  <body>
    <div class="container">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">Taxi</a>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Менеджеру<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'carpark:add_driver' %}">Добавить водителя</a></li>
                    <li><a href="{% url 'carpark:create_car' %}">Добавить машину</a></li>
                </ul>

            </li>
            <li class="dropdown"><a href="#" class="dropdown-toggle">Водителю<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'carpark:non_trip' %}">Новые заказы</a></li>
                    <li><a href="{% url 'carpark:nonclosed_trips' %}">Ваши поездки</a></li>
                </ul>

            </li>
            <li><a href="{% url 'carpark:add_trip' %}">Клиенту</a></li>
        </ul>
    </div>
    </div>
    </div>
    {% block content %} {% endblock %}
    <script type="text/javascript">
        function f(element){
            return function(){
                if(element.classList.length == 1){
                    element.classList.add("open");
                }else{
                    element.classList.remove("open");
                }
            }
        };
        var els = document.getElementsByClassName("dropdown");
        for(var i = 0; i < els.length; i++){
            els[i].onclick = f(els[i]);
        }
    </script>
  </body>
</html>